### ISSUE TITLE
V1.8 Doesn't Work

### ISSUE THREAD

**Issue by Arithium** [Skarsnik/Savestate2snes#11]
Tried with the latest version of usb2snes along with the proper files on my sd2snes. Program shows the game is patched even though I don't click Patch Rom and save states will not load or save. The other usb2snes apps work fine though. sd2snes version is 1.8.0-usb-v8 and in-game hooks are enabled.

**Comment by Skarsnik** [comment]
I don't have a good fix for that yet. You can try applying the patch with
the fileviewer app.

**Comment by tcprescott** [comment]
I just want to note that the latest pre-release version (0.5.2) works well for me on 1.8.0 firmware.

**Comment by Skarsnik** [comment]
Thanks. I can close this issue then :)
