### ISSUE TITLE
v10 of usb2snes fails firmware check

### ISSUE THREAD

**Issue by victor-acuna** [Skarsnik/Savestate2snes#12]
Just tried running this against the latest usb2snes version and I couldn't get past the version check. The application warns me about my version being "0", so I figure this is probably the line causing the problem.

https://github.com/Skarsnik/Savestate2snes/blob/96465a87bb940416a350c37b7a1e17d741244da1/usb2snes.cpp#L145

It's been years since I've done any dev in C++ so I unfortunately can't be much more useful than that.

**Comment by Skarsnik** [comment]
This should be fixed with 96465a8 and the last release :)

**Comment by victor-acuna** [comment]
Tested this latest release and it works fine, thanks! This is on an SD2SNES PRO by the way, since it's v10 of usb2snes that introduces support for the pro.

Haven't done any super heavy testing of the save states themselves yet, but this specific issue is definitely looking fixed. I'll go ahead and close it!
