### ISSUE TITLE
Possible bug patching the rom file

### ISSUE THREAD

**Issue by kidofseph** [Skarsnik/Savestate2snes#13]
Hi, I've been trying to get the Savestate2snes working on a relatively new FX Pak Pro. I have the communication working between my PC and the cartridge. I've been able to send and retrieve files over QUsb2Snes, and when I open the Savestate2snes application, it correctly reads the game that I am playing. However, when I click the "Patch ROM" button, it does nothing. The R/Y/G indicator remains yellow, indicating that I need to patch the rom file.
[log.txt](https://github.com/Skarsnik/Savestate2snes/files/4679144/log.txt)

**Comment by Skarsnik** [comment]
Use the latest release, 0.5.4 does not work with last usb2snes firmware :)

**Comment by kidofseph** [comment]
Awesome, that did it. The links must have pointed me to an older download. Thanks!
